---
# goes through and comments out all non-comment lines
- name: adjust existing sudoers
  ansible.builtin.replace:
    path: "/etc/sudoers"
    backup: true
    regexp: '^((?!#).+)$'  # match only if not commented out
    replace: '# \1'

# adds our stripped sudoers settings into /etc/sudoers
- name: put settings in place
  ansible.builtin.blockinfile:
    path: "/etc/sudoers"
    backup: true
    state: present
    insertbefore: "BOF"
    marker: "# {mark} CCDC sudoers"
    block: |
      ## generated sudoers
      Defaults !visiblepw
      Defaults always_set_home
      Defaults env_reset
      Defaults env_keep = "COLORS DISPLAY HOSTNAME HISTSIZE MAIL PS1 PS2 LANG LS_COLORS"
      Defaults env_keep += "MAIL QTDIR USERNAME LC_ADDRESS LC_CTYPE LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"
      Defaults env_keep += "LC_NAME LC_MONETARY LC_NUMERIC LC_PAPER LC_TELEPHONE LC_TIME LC_ALL LANGUAGE LINGUAS"
      Defaults env_keep += "_XKB_CHARSET XAUTHORITY"
      Defaults secure_path = /sbin:/bin:/usr/sbin:/usr/bin
      
# create stub files for users that need sudo, easier to keep track of
- name: make sure includedir is present at bottom of file
  ansible.builtin.lineinfile:
    path: "/etc/sudoers"
    state: present
    line: '#includedir /etc/sudoers.d'
    validate: /usr/sbin/visudo -csf %s

- name: ensure proper permissions
  ansible.builtin.file: 
    path: "/etc/sudoers"
    owner: root
    group: root 
    mode: '0440'
